extended rasterize_clip_space to handle dynamic batch size of clip_space_vertices
google/tf_mesh_renderer pull request #1
Opened 2019-05-28 10:10 UTC by TerisGH

using a tf.while_loop, needed for general usage of dynamic batch size

2019-05-28 10:29 UTC, TerisGH commented
I signed it!

2019-06-03 21:12 UTC, fcole requested changes
Thanks for the contribution! I'd like to get a test in that actually tests batched rendering with more than 1 image before merging this. I'll try to add that test soon.

2019-06-03 21:12 UTC, fcole commented on mesh_renderer/rasterize_triangles.py
> +  b = tf.placeholder_with_default(0, shape=[])
I think this can be a tf.constant instead of a tf.placeholder

2019-06-03 21:12 UTC, fcole commented on mesh_renderer/rasterize_triangles.py
> +    per_image_barycentric_coordinates = per_image_barycentric_coordinates.write(b, tf.reshape(barycentric_coords, [-1, 3]))
Could you reformat to 80 characters per line? I know opinions of this rule vary but that's the standard for internal Google code.

2019-06-03 21:12 UTC, fcole commented on mesh_renderer/rasterize_triangles.py
> +  def condition(b, *args):
maybe name this function something more descriptive, like "batch_loop_condition"

2019-06-03 21:12 UTC, fcole commented on mesh_renderer/rasterize_triangles.py
> +  def iteration(b, per_image_barycentric_coordinates, per_image_vertex_ids):
batch_loop_iteration?

2019-06-08 11:56 UTC, TerisGH commented
I added the requested changes. In my projects its definetly working with variable batch sizes.

2019-06-11 21:16 UTC, merged

2019-06-11 21:16 UTC, fcole commented
Merged in. Thanks for the contribution and edits!